#include <imkit/editor_core.h>
#include <imkit/video.h>
#include <imkit/cg.h>
#include <imkit/preview.h>
#include <array>
int main() {
    using namespace imkit;
    std::array<editor::Event, 32> eventStorage{};
    editor::EventBuffer events{eventStorage};
    std::array<editor::StableId, 32> ids{};
    editor::Selection selection{ids};
    auto *context = ImGui::CreateContext();
    auto &io = ImGui::GetIO();
    io.DisplaySize = {1280, 900};
    io.DeltaTime = 1.f / 60;
    io.IniFilename = nullptr;
    unsigned char *pixels = nullptr;
    int w = 0, h = 0;
    io.Fonts->GetTexDataAsRGBA32(&pixels, &w, &h);
    io.Fonts->SetTexID(ImTextureID{1});
    auto theme = MakePrecisionTheme();
    IconAtlas icons; // Texture lifetime remains with this consumer.
    for (int pixels : {16,20,24,32,48,64}) icons.SetTexture(pixels,ImTextureRef(ImTextureID{2}));
    editor::CanvasState canvas;
    editor::CurveState curve;
    editor::PropertyState property;
    editor::AssetState asset;
    editor::TimeState time;
    video::TimelineState timeline;
    cg::ViewportState viewport;
    cg::OutlinerState outliner;
    cg::UVState uv;
    curve.icons=&icons;uv.icons=&icons;viewport.icons=&icons;
    viewport.rotationAngle=0;viewport.rotationMouse={};
    editor::Transaction drag;
    ImGui::NewFrame();
    ImGui::SetNextWindowSize({1200, 800});
    ImGui::Begin("Editor API consumer");
    editor::TimeRuler("time", time, canvas, {}, 1, events, theme);
    editor::Transport(time, {});
    editor::CurveEditor("curve", {}, curve, selection, events, theme, {300, 100});
    ImGui::BeginChild("properties", {300, 100});
    editor::PropertyGrid("props", {}, property, events);
    ImGui::EndChild();
    ImGui::BeginChild("assets", {300, 100});
    editor::AssetBrowser("assets", {}, asset, selection, events);
    ImGui::EndChild();
    video::Timeline("timeline", {}, timeline, selection, events, theme, {300, 100});
    (void)video::EditTransition(video::ClipView{},false,0);
    video::ClipView keyedClip;keyedClip.keyChannel=7100;keyedClip.keyDefaultValue=1;
    auto roleTheme=MakePrecisionTheme();roleTheme.editor.effectClip=roleTheme.editor.adjustmentClip=roleTheme.editor.groupClip={1,1,1,1};
    (void)editor::EditKind::TransitionDuration;
    video::TransitionPicker("transition types",{},1,events);
    (void)video::EvaluateEnvelope({},0);
    const char *monitorLines[]={"1920 x 1080","Proxy"};
    video::MonitorOptions monitorOptions;monitorOptions.metadataPreset=video::MonitorMetadataPreset::Details;
    monitorOptions.clipName="Clip";monitorOptions.markerComment="Marker comment";monitorOptions.metadata=monitorLines;
    video::Monitor("metadata monitor",{},ImVec2{200,120},time,monitorOptions,theme);
    video::EnvelopePoint envelopePoint{8001,0,1};
    (void)envelopePoint;
    video::TrackView trackView;
    auto trackHeight=video::TrackExtent(trackView);
    (void)trackHeight;
    video::Monitor("monitor", {}, {100, 80}, time, {}, theme);
    video::Waveform("waveform", {}, {100, 20}, theme);
    video::LevelMeter("meter", {}, {}, {20, 100}, theme);
    video::AudioStripView audioStrip;
    audioStrip.id=37; audioStrip.gainId=1011; audioStrip.panId=3027;
    editor::PropertyState audioState;
    video::AudioStrip(audioStrip,1,audioState,events);
    video::Histogram("histogram", {}, {100, 50}, theme);
    video::ScopeImage("scope", {}, 0, 0, {100, 50}, theme);
    video::ScopeImage("tinted scope", {}, 0, 0, {100,50}, theme, {1,0,0,1});
    video::ColorValues colorValues;
    video::ColorState colorState;
    video::ColorControls("Color draft", colorValues);
    video::ColorControls("Color events", colorValues, {101,203,307,409,503,607}, 1, colorState, events);
    auto view = cg::BeginViewport("viewport", viewport, {}, {300, 100}, theme);
    cg::NavigateCamera(viewport.camera,{}, {},0,100);
    cg::AlignCamera(viewport.camera,cg::Axis::Z);
    cg::ViewportObjects(view, {}, viewport, selection, 1, events, theme);
    (void)cg::TransformAroundPivot({},cg::TransformTool::Rotate,cg::Axis::Z,{0,0,.2},{},{1,0,0});
    std::array<cg::TransformCompanion,2> transformCompanions{};
    viewport.companions=transformCompanions;viewport.selectedObjects={};
    cg::ObjectView geometryObject;geometryObject.geometry=700;
    (void)editor::EditKind::LinkGeometry;
    cg::TransformGizmo(view, geometryObject, viewport, 1, events, theme);
    cg::EndViewport();
    ImGui::BeginChild("outliner", {300, 100});
    cg::Outliner("tree", {}, outliner, selection, events);
    const cg::ComponentView component{123,456,"Renderer","Host-owned component"};
    cg::ComponentStack("stack",{&component,1},1,events);
    const cg::ComponentTypeView componentTypes[]={{701,"Renderer"},{709,"Wireframe"}};
    cg::ComponentStackOptions componentOptions;
    componentOptions.owner=component.owner;componentOptions.availableTypes=componentTypes;
    componentOptions.locked=false;
    cg::ComponentStack("typed stack",{&component,1},1,events,componentOptions);
    (void)editor::EditKind::ComponentAdd;
    ImGui::EndChild();
    cg::UVProvider uvProvider;
    uvProvider.all=[](void *,cg::UVSelection)->std::span<const editor::StableId>{return {};};
    uvProvider.selected=[](void *,std::span<const editor::StableId>,cg::UVSelection)->std::span<const cg::UVVertex>{return {};};
    uvProvider.selectionQuery=[](void *,editor::Rect,cg::UVSelection)->std::span<const editor::SelectablePoint>{return {};};
    uv.bindings={};uv.imageSize={1920,1080};uv.coordinates=cg::UVCoordinates::Pixel;
    uv.companionDrags={};uv.canvas.selectionPath={};uv.checker=true;uv.showTexture=false;uv.grid=true;
    cg::UVEdge edge;edge.aVertex=1;edge.bVertex=2;
    uvProvider.faces=[](void *,editor::Rect)->std::span<const cg::UVFace>{return {};};
    cg::UVEditor("uv", uvProvider, {}, uv, selection, events, theme, {300, 100});
    cg::DopeSheet("dope", {}, curve, selection, events, theme, {300, 100});
    cg::AnimationStrips("strips", {}, 1, canvas, drag, events, theme, {300, 100});
    std::array<preview::Vertex, 24> vertices;
    std::array<std::uint32_t, 36> indices;
    preview::Cube(vertices, indices);
    std::array<preview::Triangle, 12> scratch;
    preview::Mesh mesh{1, vertices, indices};
    preview::DrawListPreview(*ImGui::GetWindowDrawList(), {&mesh, 1}, {}, {0, 0}, {100, 100}, scratch);
    ImGui::End();
    ImGui::Render();
    ImGui::DestroyContext(context);
    preview::OpenGL3Renderer renderer;
    if (renderer.Init({}, 100, 100))
        return 1;
    renderer.Shutdown();
    return events.overflow ? 1 : 0;
}
