"""Build deterministic PNG variants and embedded alpha atlases from ImageGen originals.

Requires Pillow, only at asset-authoring time. Never synthesizes missing artwork.
Usage: python tools/build_icons.py [--check]
"""
from pathlib import Path
import argparse
import hashlib
import itertools
import json
import re
from PIL import Image
from design_icons import DRAWINGS, render

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets/icons'
SIZES = (12, 16, 20, 24, 32, 48, 64)


def load_catalog():
    catalog = json.loads((ASSETS / 'catalog.json').read_text(encoding='utf-8'))
    assert catalog and len(catalog) == len({x['name'] for x in catalog}), 'Unique nonempty catalog required'
    assert all(re.fullmatch(r'[A-Za-z][A-Za-z0-9]*', x['name']) and x['category'] for x in catalog)
    baseline = json.loads((ASSETS / 'stable-ids.json').read_text(encoding='utf-8'))
    assert [x['name'] for x in catalog[:len(baseline)]] == baseline, 'Existing IconId order changed'
    header = (ROOT / 'include/imkit/icons.h').read_text(encoding='utf-8')
    body = re.search(r'enum class IconId[^\{]*\{(.*?)\};', header, re.S).group(1)
    names = [x.strip().split('=')[0].strip() for x in body.split(',')]
    assert names == [x['name'] for x in catalog] + ['Count'], 'IconId/catalog mismatch'
    return catalog


def layout(catalog):
    columns = min(16, len(catalog))
    return columns, (len(catalog) + columns - 1) // columns


def build():
    catalog = load_catalog()
    columns, rows = layout(catalog)
    missing = [x['name'] for x in catalog if x['name'] not in DRAWINGS and not (ASSETS / 'originals' / (x['name'] + '.png')).exists()]
    if missing:
        raise RuntimeError('Missing generated originals: ' + ', '.join(missing))
    sources, provenance = [], []
    for item in catalog:
        path = ROOT / 'tools/design_icons.py' if item['name'] in DRAWINGS else ASSETS / 'originals' / (item['name'] + '.png')
        source = render(item['name']) if item['name'] in DRAWINGS else Image.open(path).convert('RGBA')
        alpha = source.getchannel('A')
        assert alpha.getextrema() == (0, 255), f'{path}: real transparency required'
        # Keep the generated alpha. Only normalize canvas, extent, and RGB for tinting.
        bbox = alpha.point(lambda v: 255 if v >= 128 else 0).getbbox()
        assert bbox, f'{path}: empty glyph'
        # Pad crop slightly to retain the source antialiasing fringe.
        bbox = (max(0, bbox[0]-2), max(0, bbox[1]-2),
                min(source.width, bbox[2]+2), min(source.height, bbox[3]+2))
        cropped = alpha.crop(bbox)
        sources.append(cropped)
        provenance.append(dict(name=item['name'], source=str(path.relative_to(ROOT)).replace('\\', '/'),
                               sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
                               originalSize=list(source.size), contentBounds=list(bbox)))
    encoded, offsets = [], [0]
    for size in SIZES:
        cell = size + 4
        atlas = Image.new('RGBA', (cell*columns, cell*rows), (255, 255, 255, 0))
        folder = ASSETS / str(size)
        folder.mkdir(parents=True, exist_ok=True)
        for index, (item, source) in enumerate(zip(catalog, sources)):
            extent = size * (18 / 24)
            ratio = extent / max(source.size)
            shape = source.resize((max(1, round(source.width*ratio)), max(1, round(source.height*ratio))),
                                  Image.Resampling.LANCZOS)
            alpha = Image.new('L', (size, size))
            alpha.paste(shape, ((size-shape.width)//2, (size-shape.height)//2))
            if size == 12 and 0 < alpha.getextrema()[1] < 160:
                peak = alpha.getextrema()[1]
                alpha = alpha.point(lambda value: min(255, round(value * 160 / peak)))
            icon = Image.new('RGBA', (size, size), (255, 255, 255, 0))
            icon.putalpha(alpha)
            icon.save(folder / (item['name'] + '.png'))
            atlas.paste(icon, ((index % columns)*cell+2, (index // columns)*cell+2))
        (ASSETS / 'atlases').mkdir(exist_ok=True)
        atlas.save(ASSETS / 'atlases' / f'icons-{size}.png')
        for value, group in itertools.groupby(atlas.getchannel('A').tobytes()):
            count = sum(1 for _ in group)
            while count:
                run = min(count, 255)
                encoded.extend((run, value))
                count -= run
        offsets.append(len(encoded))
    lines = ['// Generated by tools/build_icons.py. Do not edit.',
             f'constexpr int kAtlasColumns = {columns}, kAtlasRows = {rows};',
             'constexpr IconInfo kCatalog[] = {']
    lines.extend(f'    {{IconId::{x["name"]}, "{x["name"]}", "{x["category"]}"}},' for x in catalog)
    lines += ['};', 'constexpr std::size_t kOffsets[] = {' + ','.join(map(str, offsets)) + '};',
              'constexpr unsigned char kAlphaRle[] = {']
    lines.extend('    ' + ','.join(map(str, encoded[i:i+48])) + ',' for i in range(0, len(encoded), 48))
    lines += ['};', '']
    (ROOT / 'src/icons_data.inc').write_text('\n'.join(lines), encoding='utf-8')
    (ASSETS / 'provenance.json').write_text(json.dumps(provenance, indent=2) + '\n', encoding='utf-8')
    metadata = dict(count=len(catalog), categories=len({x['category'] for x in catalog}),
                    columns=columns, rows=rows, sizes=SIZES, padding=2,
                    originals=len(sources), variants=len(sources)*len(SIZES), atlases=len(SIZES))
    (ASSETS / 'metadata.json').write_text(json.dumps(metadata, indent=2) + '\n', encoding='utf-8')
    print(f'Built {len(catalog)} sources, {len(catalog)*len(SIZES)} PNG variants, {len(SIZES)} atlases; {len(encoded)} embedded RLE bytes')


def check():
    catalog = load_catalog()
    columns, rows = layout(catalog)
    metadata = json.loads((ASSETS / 'metadata.json').read_text(encoding='utf-8'))
    assert metadata == dict(count=len(catalog), categories=len({x['category'] for x in catalog}),
                            columns=columns, rows=rows, sizes=list(SIZES), padding=2,
                            originals=len(catalog), variants=len(catalog)*len(SIZES), atlases=len(SIZES))
    provenance = json.loads((ASSETS / 'provenance.json').read_text(encoding='utf-8'))
    assert [x['name'] for x in provenance] == [x['name'] for x in catalog]
    for item in provenance:
        assert hashlib.sha256((ROOT / item['source']).read_bytes()).hexdigest() == item['sha256']
    for size in SIZES:
        cell = size + 4
        atlas = Image.open(ASSETS / 'atlases' / f'icons-{size}.png')
        assert atlas.size == (cell*columns, cell*rows)
        for index, item in enumerate(catalog):
            icon = Image.open(ASSETS / str(size) / (item['name'] + '.png'))
            assert icon.mode == 'RGBA' and icon.size == (size, size)
            alpha = icon.getchannel('A')
            lo, hi = alpha.getextrema()
            assert lo == 0 and hi > 100, item['name']
            assert all(icon.getchannel(c).getextrema() == (255, 255) for c in 'RGB'), item['name']
            x, y = (index % columns)*cell+2, (index // columns)*cell+2
            assert atlas.crop((x, y, x+size, y+size)).tobytes() == icon.tobytes()
        print(f'PASS {size}px: {len(catalog)} images, alpha, tint RGB, atlas bounds and pixels')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if not args.check:
        build()
    check()
