"""Build deterministic PNG variants and embedded alpha atlases from ImageGen originals.

Requires Pillow, only at asset-authoring time. Never synthesizes missing artwork.
Usage: python tools/build_icons.py [--check]
"""
from pathlib import Path
import argparse
import hashlib
import itertools
import json
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets/icons'
SIZES = (16, 20, 24, 32, 48, 64)


def build():
    catalog = json.loads((ASSETS / 'catalog.json').read_text(encoding='utf-8'))
    assert len(catalog) == 120
    assert len({x['name'] for x in catalog}) == 120
    missing = [x['name'] for x in catalog if not (ASSETS / 'originals' / (x['name'] + '.png')).exists()]
    if missing:
        raise RuntimeError('Missing generated originals: ' + ', '.join(missing))
    sources, provenance = [], []
    for item in catalog:
        path = ASSETS / 'originals' / (item['name'] + '.png')
        source = Image.open(path).convert('RGBA')
        alpha = source.getchannel('A')
        assert alpha.getextrema() == (0, 255), f'{path}: real transparency required'
        # Keep the generated alpha. Only normalize canvas, extent, and RGB for tinting.
        bbox = alpha.point(lambda v: 255 if v >= 128 else 0).getbbox()
        assert bbox, f'{path}: empty glyph'
        # Pad crop slightly to retain the source antialiasing fringe.
        bbox = (max(0, bbox[0]-2), max(0, bbox[1]-2),
                min(source.width, bbox[2]+2), min(source.height, bbox[3]+2))
        cropped = alpha.crop(bbox)
        sources.append(cropped)
        provenance.append(dict(name=item['name'], source=str(path.relative_to(ROOT)).replace('\\', '/'),
                               sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
                               originalSize=list(source.size), contentBounds=list(bbox)))
    encoded, offsets = [], [0]
    for size in SIZES:
        cell = size + 4
        atlas = Image.new('RGBA', (cell*16, cell*8), (255, 255, 255, 0))
        folder = ASSETS / str(size)
        folder.mkdir(parents=True, exist_ok=True)
        for index, (item, source) in enumerate(zip(catalog, sources)):
            extent = size * (18 / 24)
            ratio = extent / max(source.size)
            shape = source.resize((max(1, round(source.width*ratio)), max(1, round(source.height*ratio))),
                                  Image.Resampling.LANCZOS)
            alpha = Image.new('L', (size, size))
            alpha.paste(shape, ((size-shape.width)//2, (size-shape.height)//2))
            icon = Image.new('RGBA', (size, size), (255, 255, 255, 0))
            icon.putalpha(alpha)
            icon.save(folder / (item['name'] + '.png'))
            atlas.paste(icon, ((index % 16)*cell+2, (index // 16)*cell+2))
        (ASSETS / 'atlases').mkdir(exist_ok=True)
        atlas.save(ASSETS / 'atlases' / f'icons-{size}.png')
        for value, group in itertools.groupby(atlas.getchannel('A').tobytes()):
            count = sum(1 for _ in group)
            while count:
                run = min(count, 255)
                encoded.extend((run, value))
                count -= run
        offsets.append(len(encoded))
    lines = ['// Generated by tools/build_icons.py. Do not edit.', 'constexpr IconInfo kCatalog[] = {']
    lines.extend(f'    {{IconId::{x["name"]}, "{x["name"]}", "{x["category"]}"}},' for x in catalog)
    lines += ['};', 'constexpr std::size_t kOffsets[] = {' + ','.join(map(str, offsets)) + '};',
              'constexpr unsigned char kAlphaRle[] = {']
    lines.extend('    ' + ','.join(map(str, encoded[i:i+48])) + ',' for i in range(0, len(encoded), 48))
    lines += ['};', '']
    (ROOT / 'src/icons_data.inc').write_text('\n'.join(lines), encoding='utf-8')
    (ASSETS / 'provenance.json').write_text(json.dumps(provenance, indent=2) + '\n', encoding='utf-8')
    print(f'Built {len(catalog)} originals, {len(catalog)*len(SIZES)} PNG variants, six atlases; {len(encoded)} embedded RLE bytes')


def check():
    catalog = json.loads((ASSETS / 'catalog.json').read_text(encoding='utf-8'))
    assert len(catalog) == len({x['name'] for x in catalog}) == 120
    assert len({x['category'] for x in catalog}) == 12
    for size in SIZES:
        cell = size + 4
        atlas = Image.open(ASSETS / 'atlases' / f'icons-{size}.png')
        assert atlas.size == (cell*16, cell*8)
        for index, item in enumerate(catalog):
            icon = Image.open(ASSETS / str(size) / (item['name'] + '.png'))
            assert icon.mode == 'RGBA' and icon.size == (size, size)
            alpha = icon.getchannel('A')
            lo, hi = alpha.getextrema()
            assert lo == 0 and hi > 100, item['name']
            assert all(icon.getchannel(c).getextrema() == (255, 255) for c in 'RGB'), item['name']
            x, y = (index % 16)*cell+2, (index // 16)*cell+2
            assert atlas.crop((x, y, x+size, y+size)).tobytes() == icon.tobytes()
        print(f'PASS {size}px: 120 images, alpha, tint RGB, atlas bounds and pixels')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if not args.check:
        build()
    check()
