# Kept separate so ongoing Gallery / editor work does not share implementation files.
add_library(imkit_node_editor STATIC src/node_editor.cpp src/node_layout.cpp)
add_library(imkit::node_editor ALIAS imkit_node_editor)
set_target_properties(imkit_node_editor PROPERTIES EXPORT_NAME node_editor DEBUG_POSTFIX d)
target_link_libraries(imkit_node_editor PUBLIC imkit::editor_core)
target_compile_options(imkit_node_editor PRIVATE $<$<CXX_COMPILER_ID:MSVC>:/utf-8>)
target_link_libraries(imkit_editor_suite INTERFACE imkit::node_editor)
install(TARGETS imkit_node_editor EXPORT imkitTargets ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})

if(IMKIT_BUILD_TESTS)
    add_executable(imkit_node_editor_test tests/node_editor.cpp)
    target_link_libraries(imkit_node_editor_test PRIVATE imkit::node_editor)
    add_test(NAME imkit.node_editor COMMAND imkit_node_editor_test)
    add_executable(imkit_node_editor_api_compile tests/node_editor_api_compile.cpp)
    target_link_libraries(imkit_node_editor_api_compile PRIVATE imkit::node_editor)
    add_test(NAME imkit.node_editor_api_compile COMMAND imkit_node_editor_api_compile)
endif()

if(IMKIT_BUILD_GALLERY)
    if(APPLE)
        add_executable(imkit_node_editor_gallery examples/node_editor/main_macos.mm)
    else()
        add_executable(imkit_node_editor_gallery examples/node_editor/main.cpp examples/design_gallery/capture.cpp)
    endif()
    target_compile_features(imkit_node_editor_gallery PRIVATE cxx_std_20)
    target_compile_options(imkit_node_editor_gallery PRIVATE $<$<CXX_COMPILER_ID:MSVC>:/utf-8>)
    target_compile_definitions(imkit_node_editor_gallery PRIVATE $<$<BOOL:${WIN32}>:NOMINMAX;WIN32_LEAN_AND_MEAN>)
    target_link_libraries(imkit_node_editor_gallery PRIVATE imkit::node_editor "${IMKIT_GALLERY_BACKEND_TARGET}")
    if(WIN32)
        target_link_libraries(imkit_node_editor_gallery PRIVATE windowscodecs ole32)
    else()
        target_link_libraries(imkit_node_editor_gallery PRIVATE "-framework Cocoa" "-framework Metal" "-framework QuartzCore")
        set_target_properties(imkit_node_editor_gallery PROPERTIES MACOSX_BUNDLE TRUE)
    endif()
    set_target_properties(imkit_node_editor_gallery PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/catalog")
    add_dependencies(imkit_gallery imkit_node_editor_gallery)
endif()
